"""
Django settings for TEKDB project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from glob import glob

try:
    GDAL_LIBRARY_PATH=glob('/usr/lib/libgdal.so.*')[0]
    GEOS_LIBRARY_PATH=glob('/usr/lib/libgeos_c.so.*')[0]
except IndexError as e:
    pass


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", default="set in .env file")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG", default=0)))

# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", default='*').split(" ")
ALLOWED_HOSTS = []
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(","))


# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    # 'registration',
    'leaflet',
    'nested_admin',
    'ckeditor',
    'coverage',
    'explore',
    'login',
    'TEKDB',
    'Lookup',
    'Accounts',
    'Relationships',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TEKDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'login/templates'),
            os.path.join(BASE_DIR, 'explore/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGIN_URL = '/'

WSGI_APPLICATION = 'TEKDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.contrib.gis.db.backends.postgis"),
        "NAME": os.environ.get("SQL_DATABASE", "tekdb"),
        "USER": os.environ.get("SQL_USER", "postgres"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", None),
        "HOST": os.environ.get("SQL_HOST", 'db'),
        "PORT": os.environ.get("SQL_PORT", None),
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Registration

ACCOUNT_ACTIVATION_DAYS = 14

REGISTRATION_OPEN = False


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "explore", "static"),
#    os.path.join(BASE_DIR, "TEKDB", "static"),
# ]

### DJANGO-REGISTRATION SETTINGS ###
REGISTRATION_OPEN = True


### Search Settings
SEARCH_CATEGORIES = [
    'all',
    'places',
    'resources',
    'activities',
    'citations',
    'media',
]
#Locality? People?

MIN_SEARCH_RANK = 0.01
MIN_SEARCH_SIMILARITY = 0.1

AUTH_USER_MODEL = 'Accounts.Users'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
    },
    'custom': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Format'],
            ['Bold', 'Italic', 'Underline','Strike','Subscript','Superscript'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Image','Table','HorizontalRule','SpecialChar'],
            [ 'TextColor','BGColor' ],
            ['Undo','Redo'],
            ['RemoveFormat', 'Source']
        ]
    }
}

RECORD_ICONS = {
    'activity': '/static/explore/img/activity.png',
    'citation': '/static/explore/img/citation.png',
    'place': '/static/explore/img/place.png',
    'media': '/static/explore/img/media.png',
    'event': '/static/explore/img/activity.png',
    'resource': '/static/explore/img/resource.png',
}

ADMIN_SITE_HEADER = os.environ.get("ADMIN_SITE_HEADER", default='ITK DB Admin')

TIME_ZONE = os.environ.get("TIME_ZONE", default='America/Los_Angeles')
REGISTRATION_OPEN = os.environ.get("REGISTRATION_OPEN", default=False)
DATABASE_GEOGRAPHY = {
    ###EPSG:4326###
    # 'default_lon': -124.325,
    # 'default_lat': 42.065,
    ###EPSG:3857###
    'default_lon': os.environ.get("DEFAULT_LON", default=-13839795.69),
    'default_lat': os.environ.get("DEFAULT_LAT", default=5171448.926),
    'default_zoom': os.environ.get("DEFAULT_ZOOM", default=8),
    'map_template': 'gis/admin/ol2osm.html',
    'map_extent': [
        os.environ.get("MAP_EXTENT_WEST", default=-24000000),
        os.environ.get("MAP_EXTENT_SOUTH", default=1450000),
        os.environ.get("MAP_EXTENT_EAST", default=-6200000),
        os.environ.get("MAP_EXTENT_NORTH", default=13000000)
    ], #US Territories
    'min_zoom': 2,
    'max_zoom': 19,
}
STATIC_ROOT = '/vol/web/static'
MEDIA_ROOT = '/vol/web/media'

try:
    from TEKDB.local_settings import *
except Exception as e:
    print("ERROR: Unable to load local_settings.py. This is expected for docker deployment")
