# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Relationships', '0001_initial'),
        ('Lookup', '0001_initial'),
        ('TEKDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesmediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='mediaid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='resourcesmediaevents',
            name='resourceid',
            field=models.ForeignKey(db_column='resourceid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Resources', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='resourcescitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='citationid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='resourcescitationevents',
            name='resourceid',
            field=models.ForeignKey(db_column='resourceid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Resources', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='resourceresourceevents',
            name='altresourceid',
            field=models.ForeignKey(db_column='altresourceid', on_delete=django.db.models.deletion.CASCADE, related_name='resource_b', to='TEKDB.Resources'),
        ),
        migrations.AddField(
            model_name='resourceresourceevents',
            name='resourceid',
            field=models.ForeignKey(db_column='resourceid', on_delete=django.db.models.deletion.CASCADE, related_name='resource_a', to='TEKDB.Resources'),
        ),
        migrations.AddField(
            model_name='resourcealtindigenousname',
            name='resourceid',
            field=models.ForeignKey(blank=True, db_column='resourceid', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Resources', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='resourceactivitymediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='mediaid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='resourceactivitymediaevents',
            name='resourceactivityid',
            field=models.ForeignKey(db_column='resourceactivityid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.ResourcesActivityEvents', verbose_name='resource activity'),
        ),
        migrations.AddField(
            model_name='resourceactivitycitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='citationid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='resourceactivitycitationevents',
            name='resourceactivityid',
            field=models.ForeignKey(db_column='resourceactivityid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.ResourcesActivityEvents', verbose_name='resource activity'),
        ),
        migrations.AddField(
            model_name='placesresourcemediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='mediaid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='placesresourcemediaevents',
            name='placeresourceid',
            field=models.ForeignKey(db_column='placeresourceid', on_delete=django.db.models.deletion.CASCADE, to='Relationships.PlacesResourceEvents', verbose_name='place - resource'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='customaryuse',
            field=models.ForeignKey(blank=True, db_column='customaryuse', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupCustomaryUse', verbose_name='customary use'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='partused',
            field=models.ForeignKey(blank=True, db_column='partused', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupPartUsed', verbose_name='part used'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='placeid',
            field=models.ForeignKey(db_column='placeid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='resourceid',
            field=models.ForeignKey(db_column='resourceid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Resources', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='season',
            field=models.ForeignKey(blank=True, db_column='season', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupSeason'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='timing',
            field=models.ForeignKey(blank=True, db_column='timing', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupTiming'),
        ),
        migrations.AddField(
            model_name='placesresourcecitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='citationid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='placesresourcecitationevents',
            name='placeresourceid',
            field=models.ForeignKey(db_column='placeresourceid', on_delete=django.db.models.deletion.CASCADE, to='Relationships.PlacesResourceEvents', verbose_name='place resource'),
        ),
        migrations.AddField(
            model_name='placesmediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='mediaid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='placesmediaevents',
            name='placeid',
            field=models.ForeignKey(db_column='placeid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placescitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='citationid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='placescitationevents',
            name='placeid',
            field=models.ForeignKey(db_column='placeid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placegisselections',
            name='placeid',
            field=models.ForeignKey(blank=True, db_column='placeid', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placealtindigenousname',
            name='placeid',
            field=models.ForeignKey(blank=True, db_column='placeid', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='mediacitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='citationid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='mediacitationevents',
            name='mediaid',
            field=models.ForeignKey(db_column='mediaid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='localityplaceresourceevent',
            name='localityid',
            field=models.ForeignKey(db_column='localityid', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Locality', verbose_name='locality'),
        ),
        migrations.AddField(
            model_name='localityplaceresourceevent',
            name='placeresourceid',
            field=models.ForeignKey(db_column='placeresourceid', on_delete=django.db.models.deletion.CASCADE, to='Relationships.PlacesResourceEvents', verbose_name='place resource'),
        ),
        migrations.AddField(
            model_name='localitygisselections',
            name='localityid',
            field=models.ForeignKey(blank=True, db_column='localityid', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Locality', verbose_name='locality'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcesmediaevents',
            unique_together=set([('resourceid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcescitationevents',
            unique_together=set([('resourceid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourceresourceevents',
            unique_together=set([('resourceid', 'altresourceid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourceactivitymediaevents',
            unique_together=set([('resourceactivityid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourceactivitycitationevents',
            unique_together=set([('resourceactivityid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesresourcemediaevents',
            unique_together=set([('placeresourceid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesresourcecitationevents',
            unique_together=set([('placeresourceid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesmediaevents',
            unique_together=set([('placeid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placescitationevents',
            unique_together=set([('placeid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='mediacitationevents',
            unique_together=set([('mediaid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='localityplaceresourceevent',
            unique_together=set([('placeresourceid', 'localityid')]),
        ),
    ]
