# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0003_auto_20171031_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesresourceevents',
            name='relationshipdescription',
            field=models.TextField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt'),
        ),
    ]
