# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-08 01:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Relationships", "0006_auto_20191223_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediacitationevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="excerpt/description",
            ),
        ),
        migrations.AlterField(
            model_name="placescitationevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="excerpt/description",
            ),
        ),
        migrations.AlterField(
            model_name="placesmediaevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="relationship description",
            ),
        ),
        migrations.AlterField(
            model_name="placesresourcecitationevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="excerpt/description",
            ),
        ),
        migrations.AlterField(
            model_name="placesresourceevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="excerpt",
            ),
        ),
        migrations.AlterField(
            model_name="placesresourcemediaevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="relationship description",
            ),
        ),
        migrations.AlterField(
            model_name="resourceactivitycitationevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="excerpt/description",
            ),
        ),
        migrations.AlterField(
            model_name="resourceactivitymediaevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="relationship description",
            ),
        ),
        migrations.AlterField(
            model_name="resourceresourceevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="relationship description",
            ),
        ),
        migrations.AlterField(
            model_name="resourcescitationevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="excerpt/description",
            ),
        ),
        migrations.AlterField(
            model_name="resourcesmediaevents",
            name="relationshipdescription",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="relationshipdescription",
                null=True,
                verbose_name="relationship description",
            ),
        ),
    ]
