# Generated by Django 3.2.23 on 2023-11-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Relationships", "0009_auto_20230413_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placesresourceevents",
            name="needsReview",
            field=models.BooleanField(
                db_column="needsreview", default=True, verbose_name="Needs Review"
            ),
        ),
    ]
