# Generated by Django 4.2.16 on 2025-05-08 21:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0010_alter_placesresourceevents_needsreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacitationevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt/description'),
        ),
        migrations.AlterField(
            model_name='placescitationevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt/description'),
        ),
        migrations.AlterField(
            model_name='placesmediaevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='relationship description'),
        ),
        migrations.AlterField(
            model_name='placesresourcecitationevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt/description'),
        ),
        migrations.AlterField(
            model_name='placesresourceevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='placesresourcemediaevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='relationship description'),
        ),
        migrations.AlterField(
            model_name='resourceactivitycitationevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt/description'),
        ),
        migrations.AlterField(
            model_name='resourceactivitymediaevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='relationship description'),
        ),
        migrations.AlterField(
            model_name='resourceresourceevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='relationship description'),
        ),
        migrations.AlterField(
            model_name='resourcescitationevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt/description'),
        ),
        migrations.AlterField(
            model_name='resourcesmediaevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='relationship description'),
        ),
    ]
