# Generated by Django 4.2.16 on 2025-05-12 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("TEKDB", "0025_alter_mediabulkupload_mediabulkname"),
        (
            "Relationships",
            "0011_alter_mediacitationevents_relationshipdescription_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="placesmediaevents",
            name="mediaid",
            field=models.ForeignKey(
                db_column="mediaid",
                on_delete=django.db.models.deletion.CASCADE,
                to="TEKDB.media",
                verbose_name="media",
            ),
        ),
        migrations.AlterField(
            model_name="placesmediaevents",
            name="placeid",
            field=models.ForeignKey(
                db_column="placeid",
                on_delete=django.db.models.deletion.CASCADE,
                to="TEKDB.places",
                verbose_name="place",
            ),
        ),
    ]
