# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityGISSelections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitylabel', models.CharField(blank=True, db_column='LocalityLabel', max_length=255, null=True, verbose_name='locality label')),
                ('sourcefc', models.CharField(blank=True, db_column='SourceFC', max_length=255, null=True, verbose_name='source fc')),
            ],
            options={
                'verbose_name_plural': 'Locality GIS Selections',
                'db_table': 'LocalityGISSelections',
                'managed': True,
            },
        ),
    ]
