version: '3.7'

services:
  app:
    build:
      context: .
    # image: rhodges/itkdb
    # command: dockerize -wait tcp://db:5432 sh -c "python manage.py migrate --noinput"
    # command: dockerize -wait tcp://db:5432 sh -c "python manage.py loaddata /usr/local/apps/TEKDB/TEKDB/TEKDB/fixtures/all_dummy_data.json"
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=changemeindocker-compose
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - SQL_DATABASE=tekdb
      - SQL_USER=tekdb_user
      - SQL_PASSWORD=tekdb_password
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    links:
      - db
    networks:
      - djangonetwork

  proxy:
    build:
      context: ./proxy
    # image: rhodges/itkdb_proxy
    volumes:
      - static_data:/vol/static
      # - media_data:/vol/media
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - djangonetwork

  db:
    image: postgis/postgis:14-3.1-alpine
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=tekdb_user
      - POSTGRES_PASSWORD=tekdb_password
      - POSTGRES_DB=tekdb
    ports:
      - 5432:5432
    networks:
      - djangonetwork

volumes:
  postgis-data:
  static_data:
  # media_data:

networks:
  djangonetwork:
    driver: bridge
