# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0002_auto_20170522_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queryable',
        ),
    ]
