# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupParticipants',
            fields=[
                ('participants', models.CharField(db_column='Participants', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LookupParticipants',
                'verbose_name_plural': 'participants',
                'verbose_name': 'participant',
                'managed': True,
            },
        ),
    ]
