# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lookup', '0002_lookupparticipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupActivity',
            fields=[
                ('activity', models.CharField(db_column='Activity', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'verbose_name': 'activity',
                'managed': True,
                'db_table': 'LookupActivity',
            },
        ),
        migrations.CreateModel(
            name='LookupAuthorType',
            fields=[
                ('authortype', models.CharField(db_column='AuthorType', max_length=50, primary_key=True, serialize=False, verbose_name='author type')),
            ],
            options={
                'verbose_name_plural': 'author types',
                'verbose_name': 'author type',
                'managed': True,
                'db_table': 'LookupAuthorType',
            },
        ),
        migrations.CreateModel(
            name='LookupTechniques',
            fields=[
                ('techniques', models.CharField(db_column='Techniques', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'techniques',
                'verbose_name': 'technique',
                'managed': True,
                'db_table': 'LookupTechniques',
            },
        ),
        migrations.CreateModel(
            name='LookupUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=100, null=True, verbose_name='username')),
                ('usingcustomusername', models.BooleanField(db_column='UsingCustomUsername', default=False, verbose_name='using custom username')),
                ('usertitle', models.CharField(blank=True, db_column='UserTitle', max_length=100, null=True, verbose_name='title')),
                ('useraffiliation', models.CharField(blank=True, db_column='UserAffiliation', max_length=100, null=True, verbose_name='affiliation')),
            ],
            options={
                'verbose_name_plural': 'user info',
                'verbose_name': 'user info',
                'managed': True,
                'db_table': 'LookupUserInfo',
            },
        ),
    ]
