# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-07 20:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lookup', '0003_auto_20191223_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='relationshiptootherpeople',
            field=ckeditor.fields.RichTextField(blank=True, db_column='relationshiptootherpeople', null=True, verbose_name='relationship to other people'),
        ),
    ]
