# Generated by Django 3.2.8 on 2021-10-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lookup', '0004_auto_20200107_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupuserinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
