# Generated by Django 4.2.16 on 2025-05-08 21:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("Lookup", "0005_alter_lookupuserinfo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="relationshiptootherpeople",
            field=tinymce.models.HTMLField(
                blank=True,
                db_column="relationshiptootherpeople",
                null=True,
                verbose_name="relationship to other people",
            ),
        ),
    ]
