# Generated by Django 3.2.13 on 2022-05-10 16:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20220506_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='max_results_returned',
            field=models.IntegerField(default=500, help_text='500 is recommended. Allowing more may result in poor website performance or strain on the server.', verbose_name='Maximum no. of search results'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='homepage_font_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Text color on homepage. Recommended: White (#FFFFFF).', image_field=None, max_length=18, samples=[('#8f371c', 'primary_a'), ('#f7f3eb', 'primary_b'), ('#0e1522', 'primary_c'), ('#ced2da', 'primary_d'), ('#51723b', 'secondary_a'), ('#839230', 'secondary_b'), ('#6ea32e', 'secondary_c'), ('#b44ba3', 'secondary_d'), ('#FFFFFF', 'white'), ('#000000', 'black')], verbose_name='Homepage Text Color'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='homepage_left_background',
            field=colorfield.fields.ColorField(default='#000000', help_text='Background color behind Text on homepage. Recommended: Black (#000000).', image_field=None, max_length=18, samples=[('#8f371c', 'primary_a'), ('#f7f3eb', 'primary_b'), ('#0e1522', 'primary_c'), ('#ced2da', 'primary_d'), ('#51723b', 'secondary_a'), ('#839230', 'secondary_b'), ('#6ea32e', 'secondary_c'), ('#b44ba3', 'secondary_d'), ('#FFFFFF', 'white'), ('#000000', 'black')], verbose_name='Left Homepage Background Color'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='homepage_right_background',
            field=colorfield.fields.ColorField(default='#000000', help_text='Background color behind image on homepage. Recommended: Black (#000000).', image_field=None, max_length=18, samples=[('#8f371c', 'primary_a'), ('#f7f3eb', 'primary_b'), ('#0e1522', 'primary_c'), ('#ced2da', 'primary_d'), ('#51723b', 'secondary_a'), ('#839230', 'secondary_b'), ('#6ea32e', 'secondary_c'), ('#b44ba3', 'secondary_d'), ('#FFFFFF', 'white'), ('#000000', 'black')], verbose_name='Right Homepage Background Color'),
        ),
    ]
