# Generated by Django 3.2.13 on 2022-05-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0005_auto_20220510_0939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="logo",
            field=models.CharField(
                choices=[
                    ("/static/explore/img/logos/logo_weave.svg", "Weave"),
                    ("/static/explore/img/logos/logo_drop.svg", "Droplet"),
                    ("Other", "Custom"),
                ],
                default=("/static/explore/img/logos/logo_weave.svg", "Weave"),
                help_text='Choose your logo for the site header. You can choose between: <ul><li style="padding-left: 1rem">\'Weave\' <img src="/static/explore/img/logos/logo_weave.svg" style="max-width: 70px; padding:0.5rem; background-color:white"></li><li style="padding-left: 1rem">\'Droplet\' <img src="/static/explore/img/logos/logo_drop.svg" style="max-width: 70px; padding:0.5rem; background-color:white"></li><li>Or choose \'Custom\' and add your own using the <b>Header Logo Override Image</b> field.</li></ul>',
                max_length=255,
            ),
        ),
    ]
