# Generated by Django 3.2.25 on 2024-09-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_auto_20240913_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='preferredInitialism',
            field=models.CharField(blank=True, default='ITK', help_text="Suggestions: 'ITK', 'TEK', etc...", max_length=15, verbose_name='Preferred sharthand for traditional knowledge'),
        ),
    ]
