# Generated by Django 3.2.25 on 2024-10-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_alter_configuration_preferredinitialismplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='preferredInitialismPlacement',
            field=models.CharField(choices=[('default', 'Align Center'), ('before', 'Align Left'), ('after', 'Align Right')], default=('default', 'Align Center'), help_text='Select the position of the preferred initialism in relative to the logo.', max_length=255),
        ),
    ]
