services:
  db:
    extends:
      file: common.yaml
      service: db

  web:
    extends:
      file: common.yaml
      service: web
    image: ${ITKDB_ECR_PATH}:latest
    command: ["prod"]
    env_file:
      - .env.prod
    ports: []
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
  proxy:
    image: ${ITKDB_PROXY_ECR_PATH}:latest
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:8080"
    volumes:
      - static_volume:/vol/static/static:ro
      - media_volume:/vol/static/media:ro
  redis:
    extends:
      file: common.yaml
      service: redis
  celery:
    extends:
      file: common.yaml
      service: celery
    image: ${ITKDB_ECR_PATH}:latest
    env_file:
      - .env.prod
    volumes:
      - media_volume:/usr/src/app/media
  celery-beat:
    extends:
      file: common.yaml
      service: celery-beat
    image: ${ITKDB_ECR_PATH}:latest
    env_file:
      - .env.prod
    volumes:
      - media_volume:/usr/src/app/media

volumes:
  tekdb_db_data:
  static_volume:
  media_volume:
