services:
  db:
    extends:
      file: common.yaml
      service: db

  web:
    extends:
      file: common.yaml
      service: web
    image: ${WEB_IMAGE}:latest
    command: ["prod-local"]
    env_file:
      - path: .env.dev
        required: true
    ports: []
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - static_volume:/usr/src/app/static
      - ../../media:/usr/src/app/media
  proxy:
    container_name: tekdb_proxy
    build:
      context: ../proxy/
      dockerfile: ../proxy/Dockerfile.local
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:8080"
    volumes:
      - static_volume:/vol/static/static:ro
      - ../../media:/vol/static/media:ro
  redis:
    extends:
      file: common.yaml
      service: redis
  celery:
    build: ../TEKDB/
    volumes:
      - ../TEKDB:/usr/src/app
    extends:
      file: common.yaml
      service: celery
  celery-beat:
    build: ../TEKDB/
    volumes:
      - ../TEKDB:/usr/src/app
    extends:
      file: common.yaml
      service: celery-beat

volumes:
  tekdb_db_data:
  static_volume:
