# Generated by Django 4.2.29 on 2026-03-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.CharField(max_length=50, null=True)),
                ('original_created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='age_policy', max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Partial Upload Deletion Log',
                'verbose_name_plural': 'Partial Upload Deletion Logs',
                'indexes': [models.Index(fields=['deleted_at'], name='Logs_mediaf_deleted_17c511_idx')],
            },
        ),
    ]
