# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 02:22
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('citationid', models.AutoField(db_column='CitationID', primary_key=True, serialize=False)),
                ('referencetext', models.CharField(blank=True, db_column='ReferenceText', max_length=50, null=True, verbose_name='description')),
                ('authorprimary', models.CharField(blank=True, db_column='AuthorPrimary', max_length=255, null=True, verbose_name='primary author')),
                ('authorsecondary', models.CharField(blank=True, db_column='AuthorSecondary', max_length=255, null=True, verbose_name='secondary author')),
                ('placeofinterview', models.CharField(blank=True, db_column='PlaceofInterview', max_length=255, null=True, verbose_name='place of interview')),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('seriestitle', models.CharField(blank=True, db_column='SeriesTitle', max_length=255, null=True, verbose_name='series title')),
                ('seriesvolume', models.CharField(blank=True, db_column='SeriesVolume', max_length=50, null=True, verbose_name='series volume')),
                ('serieseditor', models.CharField(blank=True, db_column='SeriesEditor', max_length=255, null=True, verbose_name='series editor')),
                ('publisher', models.CharField(blank=True, db_column='Publisher', max_length=100, null=True)),
                ('publishercity', models.CharField(blank=True, db_column='PublisherCity', max_length=255, null=True, verbose_name='city')),
                ('preparedfor', models.CharField(blank=True, db_column='PreparedFor', max_length=100, null=True, verbose_name='prepared_for')),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'db_table': 'Citations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CurrentVersion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('backendversion', models.IntegerField(blank=True, db_column='BackendVersion', null=True, verbose_name='backend version')),
                ('frontendversion', models.IntegerField(blank=True, db_column='FrontendVersion', null=True, verbose_name='frontend version')),
            ],
            options={
                'db_table': 'CurrentVersion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('localityid', models.AutoField(db_column='LocalityID', primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, db_column='EnglishName', max_length=255, null=True, verbose_name='english name')),
                ('indigenousname', models.CharField(blank=True, db_column='IndigenousName', max_length=255, null=True, verbose_name='indigenous name')),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
                'db_table': 'Locality',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocalityGISSelections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitylabel', models.CharField(blank=True, db_column='LocalityLabel', max_length=255, null=True, verbose_name='locality label')),
                ('sourcefc', models.CharField(blank=True, db_column='SourceFC', max_length=255, null=True, verbose_name='source fc')),
                ('localityid', models.ForeignKey(blank=True, db_column='LocalityID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Locality', verbose_name='locality')),
            ],
            options={
                'db_table': 'LocalityGISSelections',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupActivity',
            fields=[
                ('activity', models.CharField(db_column='Activity', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LookupActivity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupAuthorType',
            fields=[
                ('authortype', models.CharField(db_column='AuthorType', max_length=50, primary_key=True, serialize=False, verbose_name='author type')),
            ],
            options={
                'db_table': 'LookupAuthorType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupCustomaryUse',
            fields=[
                ('usedfor', models.CharField(db_column='UsedFor', max_length=255, primary_key=True, serialize=False, verbose_name='used_for')),
            ],
            options={
                'db_table': 'LookupCustomaryUse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupHabitat',
            fields=[
                ('habitat', models.CharField(db_column='Habitat', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LookupHabitat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupLocalityType',
            fields=[
                ('localitytype', models.CharField(db_column='LocalityType', max_length=255, primary_key=True, serialize=False, verbose_name='locality type')),
            ],
            options={
                'db_table': 'LookupLocalityType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupMediaType',
            fields=[
                ('mediatype', models.CharField(db_column='MediaType', max_length=255, primary_key=True, serialize=False, verbose_name='type')),
                ('mediacategory', models.CharField(blank=True, db_column='MediaCategory', max_length=255, null=True, verbose_name='category')),
            ],
            options={
                'db_table': 'LookupMediaType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupParticipants',
            fields=[
                ('participants', models.CharField(db_column='Participants', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LookupParticipants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupPartUsed',
            fields=[
                ('partused', models.CharField(db_column='PartUsed', max_length=255, primary_key=True, serialize=False, verbose_name='part used')),
            ],
            options={
                'db_table': 'LookupPartUsed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupPlanningUnit',
            fields=[
                ('planningunitid', models.IntegerField(db_column='PlanningUnitID', primary_key=True, serialize=False)),
                ('planningunitname', models.CharField(blank=True, db_column='PlanningUnitName', max_length=100, null=True, verbose_name='planning unit')),
            ],
            options={
                'db_table': 'LookupPlanningUnit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupReferenceType',
            fields=[
                ('documenttype', models.CharField(db_column='DocumentType', max_length=25, primary_key=True, serialize=False, verbose_name='document type')),
            ],
            options={
                'db_table': 'LookupReferenceType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupResourceGroup',
            fields=[
                ('resourceclassificationgroup', models.CharField(db_column='ResourceClassificationGroup', max_length=255, primary_key=True, serialize=False, verbose_name='broad species group')),
            ],
            options={
                'db_table': 'LookupResourceGroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupSeason',
            fields=[
                ('season', models.CharField(db_column='Season', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LookupSeason',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupTechniques',
            fields=[
                ('techniques', models.CharField(db_column='Techniques', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LookupTechniques',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupTiming',
            fields=[
                ('timing', models.CharField(db_column='Timing', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LookupTiming',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupTribe',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tribeunit', models.CharField(blank=True, db_column='TribeUnit', max_length=50, null=True, verbose_name='tribe subunit')),
                ('tribe', models.CharField(blank=True, db_column='Tribe', max_length=100, null=True, verbose_name='tribe')),
                ('federaltribe', models.CharField(blank=True, db_column='FederalTribe', max_length=100, null=True, verbose_name='tribal government')),
            ],
            options={
                'db_table': 'LookupTribe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=100, null=True, verbose_name='username')),
                ('usingcustomusername', models.BooleanField(db_column='UsingCustomUsername', default=False, verbose_name='using custom username')),
                ('usertitle', models.CharField(blank=True, db_column='UserTitle', max_length=100, null=True, verbose_name='title')),
                ('useraffiliation', models.CharField(blank=True, db_column='UserAffiliation', max_length=100, null=True, verbose_name='affiliation')),
            ],
            options={
                'db_table': 'LookupUserInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('mediaid', models.AutoField(db_column='MediaID', primary_key=True, serialize=False)),
                ('medianame', models.CharField(blank=True, db_column='MediaName', max_length=255, null=True, verbose_name='name')),
                ('mediadescription', models.TextField(blank=True, db_column='MediaDescription', null=True, verbose_name='description')),
                ('medialink', models.CharField(blank=True, db_column='MediaLink', max_length=255, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Medium',
                'verbose_name_plural': 'Media',
                'db_table': 'Media',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('personid', models.AutoField(db_column='PersonID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=255, null=True, verbose_name='first name')),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=255, null=True, verbose_name='last name')),
                ('yearborn', models.IntegerField(blank=True, db_column='YearBorn', null=True, verbose_name='year born')),
                ('village', models.CharField(blank=True, db_column='Village', max_length=255, null=True)),
                ('relationshiptootherpeople', models.TextField(blank=True, db_column='RelationshipToOtherPeople', null=True, verbose_name='relationship to other people')),
            ],
            options={
                'db_table': 'People',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceAltIndigenousName',
            fields=[
                ('altindigenousnameid', models.AutoField(db_column='AltIndigenousNameID', primary_key=True, serialize=False)),
                ('altindigenousname', models.CharField(blank=True, db_column='AltIndigenousName', max_length=255, null=True, verbose_name='alternate indigenous name')),
            ],
            options={
                'verbose_name': 'Place - Indigenous Name',
                'verbose_name_plural': 'Places - Indigenous Names',
                'db_table': 'PlaceAltIndigenousName',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceGISSelections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placelabel', models.CharField(blank=True, db_column='PlaceLabel', max_length=255, null=True, verbose_name='label')),
                ('sourcefc', models.CharField(blank=True, db_column='SourceFC', max_length=255, null=True, verbose_name='source fc')),
            ],
            options={
                'db_table': 'PlaceGISSelections',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('placeid', models.AutoField(db_column='PlaceID', primary_key=True, serialize=False)),
                ('indigenousplacename', models.CharField(blank=True, db_column='IndigenousPlaceName', max_length=255, null=True, verbose_name='indigenous name')),
                ('indigenousplacenamemeaning', models.CharField(blank=True, db_column='IndigenousPlaceNameMeaning', max_length=255, null=True, verbose_name='english translation')),
                ('englishplacename', models.CharField(blank=True, db_column='EnglishPlaceName', max_length=255, null=True, verbose_name='english name')),
                ('islocked', models.BooleanField(db_column='IsLocked', default=False, verbose_name='locked?')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'db_table': 'Places',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlacesResourceEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('placeresourceid', models.AutoField(db_column='PlaceResourceID', primary_key=True, serialize=False)),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('barterresource', models.BooleanField(db_column='BarterResource', default=False, verbose_name='barter resource?')),
                ('january', models.BooleanField(db_column='January', default=False)),
                ('february', models.BooleanField(db_column='February', default=False)),
                ('march', models.BooleanField(db_column='March', default=False)),
                ('april', models.BooleanField(db_column='April', default=False)),
                ('may', models.BooleanField(db_column='May', default=False)),
                ('june', models.BooleanField(db_column='June', default=False)),
                ('july', models.BooleanField(db_column='July', default=False)),
                ('august', models.BooleanField(db_column='August', default=False)),
                ('september', models.BooleanField(db_column='September', default=False)),
                ('october', models.BooleanField(db_column='October', default=False)),
                ('november', models.BooleanField(db_column='November', default=False)),
                ('december', models.BooleanField(db_column='December', default=False)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('islocked', models.BooleanField(db_column='IsLocked', default=False, verbose_name='locked?')),
            ],
            options={
                'verbose_name': 'Place - Resource',
                'verbose_name_plural': 'Places - Resources',
                'db_table': 'PlacesResourceEvents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceAltIndigenousName',
            fields=[
                ('altindigenousnameid', models.AutoField(db_column='AltIndigenousNameID', primary_key=True, serialize=False)),
                ('altindigenousname', models.CharField(blank=True, db_column='AltIndigenousName', max_length=255, null=True, verbose_name='alt indigenous name')),
            ],
            options={
                'db_table': 'ResourceAltIndigenousName',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('resourceid', models.AutoField(db_column='ResourceID', primary_key=True, serialize=False)),
                ('commonname', models.CharField(blank=True, db_column='CommonName', max_length=255, null=True, unique=True, verbose_name='common name')),
                ('indigenousname', models.CharField(blank=True, db_column='IndigenousName', max_length=255, null=True, verbose_name='indigenous name')),
                ('genus', models.CharField(blank=True, db_column='Genus', max_length=255, null=True, verbose_name='genus')),
                ('species', models.CharField(blank=True, db_column='Species', max_length=255, null=True)),
                ('specific', models.BooleanField(db_column='Specific', default=False)),
                ('islocked', models.BooleanField(db_column='IsLocked', default=False, verbose_name='locked?')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'Resources',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourcesActivityEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('resourceactivityid', models.AutoField(db_column='ResourceActivityID', primary_key=True, serialize=False)),
                ('relationshipdescription', models.TextField(blank=True, db_column='RelationshipDescription', null=True, verbose_name='relationship description')),
                ('activitylongdescription', models.TextField(blank=True, db_column='ActivityLongDescription', null=True, verbose_name='full activity description')),
                ('gear', models.CharField(blank=True, db_column='Gear', max_length=255, null=True)),
                ('customaryuse', models.CharField(blank=True, db_column='CustomaryUse', max_length=255, null=True, verbose_name='customary use')),
                ('timingdescription', models.CharField(blank=True, db_column='TimingDescription', max_length=255, null=True, verbose_name='timing description')),
                ('islocked', models.BooleanField(db_column='IsLocked', default=False, verbose_name='locked?')),
            ],
            options={
                'db_table': 'ResourcesActivityEvents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('accessid', models.AutoField(db_column='AccessID', primary_key=True, serialize=False)),
                ('accesslevel', models.CharField(blank=True, db_column='AccessLevel', max_length=255, null=True, verbose_name='access level')),
            ],
            options={
                'db_table': 'UserAccess',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('first_name', models.CharField(db_column='FirstName', max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(db_column='LastName', max_length=255, verbose_name='last name')),
                ('affiliation', models.CharField(db_column='Affiliation', max_length=255)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('accesslevel', models.ForeignKey(db_column='AccessLevel', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.UserAccess', verbose_name='access level')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LocalityPlaceResourceEvent',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('placeresourceid', models.ForeignKey(db_column='PlaceResourceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.PlacesResourceEvents', verbose_name='place resource')),
            ],
            options={
                'db_table': 'LocalityPlaceResourceEvent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MediaCitationEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('mediaid', models.ForeignKey(db_column='MediaID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.Media', verbose_name='media')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=255, null=True)),
            ],
            options={
                'db_table': 'MediaCitationEvents',
                'verbose_name_plural': 'Media - Citations',
                'verbose_name': 'Medium - Citation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlacesCitationEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('placeid', models.ForeignKey(db_column='PlaceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.Places', verbose_name='place')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PlacesCitationEvents',
                'verbose_name_plural': 'Places - Citations',
                'verbose_name': 'Place - Citation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlacesMediaEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('placeid', models.ForeignKey(db_column='PlaceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.Places', verbose_name='place')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PlacesMediaEvents',
                'verbose_name_plural': 'Places - Media',
                'verbose_name': 'Place - Medium',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlacesResourceCitationEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('placeresourceid', models.ForeignKey(db_column='PlaceResourceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.PlacesResourceEvents', verbose_name='place resource')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PlacesResourceCitationEvents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlacesResourceMediaEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('placeresourceid', models.ForeignKey(db_column='PlaceResourceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.PlacesResourceEvents', verbose_name='place - resource')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PlacesResourceMediaEvents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceActivityCitationEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('resourceactivityid', models.ForeignKey(db_column='ResourceActivityID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.ResourcesActivityEvents', verbose_name='resource activity')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ResourceActivityCitationEvents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceActivityMediaEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('resourceactivityid', models.ForeignKey(db_column='ResourceActivityID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.ResourcesActivityEvents', verbose_name='resource activity')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ResourceActivityMediaEvents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceResourceEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('resourceid', models.ForeignKey(db_column='ResourceID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resource_a', serialize=False, to='TEKDB.Resources')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
            ],
            options={
                'db_table': 'ResourceResourceEvents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourcesCitationEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('resourceid', models.ForeignKey(db_column='ResourceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.Resources', verbose_name='resource')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ResourcesCitationEvents',
                'verbose_name_plural': 'Resources - Citations',
                'verbose_name': 'Resource - Citation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourcesMediaEvents',
            fields=[
                ('enteredbyname', models.CharField(blank=True, db_column='EnteredByName', max_length=25, null=True, verbose_name='entered by name')),
                ('enteredbytribe', models.CharField(blank=True, db_column='EnteredByTribe', max_length=100, null=True, verbose_name='entered by tribe')),
                ('enteredbytitle', models.CharField(blank=True, db_column='EnteredByTitle', max_length=100, null=True, verbose_name='entered by title')),
                ('enteredbydate', models.DateTimeField(auto_now_add=True, db_column='EnteredByDate', null=True, verbose_name='entered by date')),
                ('modifiedbyname', models.CharField(blank=True, db_column='ModifiedByName', max_length=25, null=True, verbose_name='modified by name')),
                ('modifiedbytitle', models.CharField(blank=True, db_column='ModifiedByTitle', max_length=100, null=True, verbose_name='modified by title')),
                ('modifiedbytribe', models.CharField(blank=True, db_column='ModifiedByTribe', max_length=100, null=True, verbose_name='modified by tribe')),
                ('modifiedbydate', models.DateTimeField(auto_now=True, db_column='ModifiedByDate', null=True, verbose_name='modified by date')),
                ('resourceid', models.ForeignKey(db_column='ResourceID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TEKDB.Resources', verbose_name='resource')),
                ('relationshipdescription', models.CharField(blank=True, db_column='RelationshipDescription', max_length=255, null=True, verbose_name='relationship description')),
                ('pages', models.CharField(blank=True, db_column='Pages', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ResourcesMediaEvents',
                'verbose_name_plural': 'Resources - Media',
                'verbose_name': 'Resource - Medium',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='activityshortdescription',
            field=models.ForeignKey(blank=True, db_column='ActivityShortDescription', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupActivity', verbose_name='activity type'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='participants',
            field=models.ForeignKey(blank=True, db_column='Participants', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupParticipants'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='partused',
            field=models.ForeignKey(blank=True, db_column='PartUsed', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupPartUsed', verbose_name='part used'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='placeresourceid',
            field=models.ForeignKey(db_column='PlaceResourceID', on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.PlacesResourceEvents', verbose_name='place resource'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='technique',
            field=models.ForeignKey(blank=True, db_column='Technique', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupTechniques'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='timing',
            field=models.ForeignKey(blank=True, db_column='Timing', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupTiming'),
        ),
        migrations.AddField(
            model_name='resources',
            name='resourceclassificationgroup',
            field=models.ForeignKey(blank=True, db_column='ResourceClassificationGroup', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupResourceGroup', verbose_name='broad species group'),
        ),
        migrations.AddField(
            model_name='resourcealtindigenousname',
            name='resourceid',
            field=models.ForeignKey(blank=True, db_column='ResourceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Resources', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='customaryuse',
            field=models.ForeignKey(blank=True, db_column='CustomaryUse', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupCustomaryUse', verbose_name='customary use'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='partused',
            field=models.ForeignKey(blank=True, db_column='PartUsed', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupPartUsed', verbose_name='part used'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='placeid',
            field=models.ForeignKey(db_column='PlaceID', on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='resourceid',
            field=models.ForeignKey(db_column='ResourceID', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Resources', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='season',
            field=models.ForeignKey(blank=True, db_column='Season', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupSeason'),
        ),
        migrations.AddField(
            model_name='placesresourceevents',
            name='timing',
            field=models.ForeignKey(blank=True, db_column='Timing', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupTiming'),
        ),
        migrations.AddField(
            model_name='places',
            name='planningunitid',
            field=models.ForeignKey(blank=True, db_column='PlanningUnitID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupPlanningUnit', verbose_name='planning unit'),
        ),
        migrations.AddField(
            model_name='places',
            name='primaryhabitat',
            field=models.ForeignKey(blank=True, db_column='PrimaryHabitat', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupHabitat', verbose_name='primary habitat'),
        ),
        migrations.AddField(
            model_name='places',
            name='tribeid',
            field=models.ForeignKey(blank=True, db_column='TribeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupTribe', verbose_name='tribe'),
        ),
        migrations.AddField(
            model_name='placegisselections',
            name='placeid',
            field=models.ForeignKey(blank=True, db_column='PlaceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placealtindigenousname',
            name='placeid',
            field=models.ForeignKey(blank=True, db_column='PlaceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='media',
            name='mediatype',
            field=models.ForeignKey(blank=True, db_column='MediaType', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupMediaType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='locality',
            name='localitytype',
            field=models.ForeignKey(blank=True, db_column='LocalityType', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupLocalityType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='locality',
            name='placeid',
            field=models.ForeignKey(blank=True, db_column='PlaceID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='citations',
            name='authortype',
            field=models.ForeignKey(blank=True, db_column='AuthorType', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupAuthorType', verbose_name='author type'),
        ),
        migrations.AddField(
            model_name='citations',
            name='intervieweeid',
            field=models.ForeignKey(blank=True, db_column='IntervieweeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewee', to='TEKDB.People', verbose_name='interviewee'),
        ),
        migrations.AddField(
            model_name='citations',
            name='interviewerid',
            field=models.ForeignKey(blank=True, db_column='InterviewerID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='TEKDB.People', verbose_name='interviewer'),
        ),
        migrations.AddField(
            model_name='citations',
            name='referencetype',
            field=models.ForeignKey(db_column='ReferenceType', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.LookupReferenceType', verbose_name='reference type'),
        ),
        migrations.AddField(
            model_name='resourcesmediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='MediaID', on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='resourcescitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='CitationID', on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='resourceresourceevents',
            name='altresourceid',
            field=models.ForeignKey(db_column='AltResourceID', on_delete=django.db.models.deletion.CASCADE, related_name='resource_b', to='TEKDB.Resources'),
        ),
        migrations.AddField(
            model_name='resourceactivitymediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='MediaID', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='resourceactivitycitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='CitationID', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='placesresourcemediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='MediaID', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='placesresourcecitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='CitationID', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='placesmediaevents',
            name='mediaid',
            field=models.ForeignKey(db_column='MediaID', on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='placescitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='CitationID', on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='mediacitationevents',
            name='citationid',
            field=models.ForeignKey(db_column='CitationID', on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Citations', verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='localityplaceresourceevent',
            name='localityid',
            field=models.ForeignKey(db_column='LocalityID', on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Locality', verbose_name='locality'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcesmediaevents',
            unique_together=set([('resourceid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourcescitationevents',
            unique_together=set([('resourceid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourceresourceevents',
            unique_together=set([('resourceid', 'altresourceid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourceactivitymediaevents',
            unique_together=set([('resourceactivityid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='resourceactivitycitationevents',
            unique_together=set([('resourceactivityid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesresourcemediaevents',
            unique_together=set([('placeresourceid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesresourcecitationevents',
            unique_together=set([('placeresourceid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placesmediaevents',
            unique_together=set([('placeid', 'mediaid')]),
        ),
        migrations.AlterUniqueTogether(
            name='placescitationevents',
            unique_together=set([('placeid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='mediacitationevents',
            unique_together=set([('mediaid', 'citationid')]),
        ),
        migrations.AlterUniqueTogether(
            name='localityplaceresourceevent',
            unique_together=set([('placeresourceid', 'localityid')]),
        ),
    ]
