# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=3857, verbose_name='Place Geometry'),
        ),
    ]
