# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='journal',
            field=models.TextField(blank=True, db_column='journal', null=True, verbose_name='journal'),
        ),
        migrations.AddField(
            model_name='citations',
            name='journalpages',
            field=models.TextField(blank=True, db_column='journalpages', null=True, verbose_name='journal pages'),
        ),
    ]
