# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lookup', '0001_initial'),
        ('Relationships', '0002_auto_20170610_1931'),
        ('TEKDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='placeresourceid',
            field=models.ForeignKey(db_column='PlaceResourceID', on_delete=django.db.models.deletion.DO_NOTHING, to='Relationships.PlacesResourceEvents', verbose_name='place resource'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='technique',
            field=models.ForeignKey(blank=True, db_column='Technique', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupTechniques'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='timing',
            field=models.ForeignKey(blank=True, db_column='Timing', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupTiming'),
        ),
        migrations.AddField(
            model_name='resources',
            name='resourceclassificationgroup',
            field=models.ForeignKey(blank=True, db_column='ResourceClassificationGroup', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupResourceGroup', verbose_name='broad species group'),
        ),
        migrations.AddField(
            model_name='places',
            name='planningunitid',
            field=models.ForeignKey(blank=True, db_column='PlanningUnitID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupPlanningUnit', verbose_name='planning unit'),
        ),
        migrations.AddField(
            model_name='places',
            name='primaryhabitat',
            field=models.ForeignKey(blank=True, db_column='PrimaryHabitat', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupHabitat', verbose_name='primary habitat'),
        ),
        migrations.AddField(
            model_name='places',
            name='tribeid',
            field=models.ForeignKey(blank=True, db_column='TribeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupTribe', verbose_name='tribe'),
        ),
        migrations.AddField(
            model_name='media',
            name='mediatype',
            field=models.ForeignKey(blank=True, db_column='MediaType', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupMediaType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='locality',
            name='localitytype',
            field=models.ForeignKey(blank=True, db_column='LocalityType', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupLocalityType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='locality',
            name='placeid',
            field=models.ForeignKey(blank=True, db_column='PlaceID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TEKDB.Places', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='citations',
            name='authortype',
            field=models.ForeignKey(blank=True, db_column='AuthorType', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupAuthorType', verbose_name='author type'),
        ),
        migrations.AddField(
            model_name='citations',
            name='intervieweeid',
            field=models.ForeignKey(blank=True, db_column='IntervieweeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewee', to='Lookup.People', verbose_name='interviewee'),
        ),
        migrations.AddField(
            model_name='citations',
            name='interviewerid',
            field=models.ForeignKey(blank=True, db_column='InterviewerID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='Lookup.People', verbose_name='interviewer'),
        ),
        migrations.AddField(
            model_name='citations',
            name='referencetype',
            field=models.ForeignKey(db_column='ReferenceType', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='Lookup.LookupReferenceType', verbose_name='reference type'),
        ),
    ]
