# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-24 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TEKDB", "0002_auto_20171031_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="places",
            name="indigenousplacenamemeaning",
            field=models.TextField(
                blank=True,
                db_column="indigenousplacenamemeaning",
                null=True,
                verbose_name="english translation",
            ),
        ),
    ]
