# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0002_places_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='DigitizedBy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='digitized by'),
        ),
        migrations.AddField(
            model_name='places',
            name='DigitizedDate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='digitized date'),
        ),
        migrations.AddField(
            model_name='places',
            name='Source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='source'),
        ),
    ]
