# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0003_delete_queryable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citations',
            options={'managed': True, 'verbose_name': 'Citation', 'verbose_name_plural': 'Citations'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'managed': True, 'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
        migrations.AlterModelOptions(
            name='localityplaceresourceevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lookupplanningunit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lookuptribe',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'managed': True, 'verbose_name': 'Medium', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='mediacitationevents',
            options={'managed': True, 'verbose_name': 'Medium - Citation', 'verbose_name_plural': 'Media - Citations'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='placealtindigenousname',
            options={'managed': True, 'verbose_name': 'Place - Indigenous Name', 'verbose_name_plural': 'Places - Indigenous Names'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'managed': True, 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='placescitationevents',
            options={'managed': True, 'verbose_name': 'Place - Citation', 'verbose_name_plural': 'Places - Citations'},
        ),
        migrations.AlterModelOptions(
            name='placesmediaevents',
            options={'managed': True, 'verbose_name': 'Place - Medium', 'verbose_name_plural': 'Places - Media'},
        ),
        migrations.AlterModelOptions(
            name='placesresourcecitationevents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='placesresourceevents',
            options={'managed': True, 'verbose_name': 'Place - Resource', 'verbose_name_plural': 'Places - Resources'},
        ),
        migrations.AlterModelOptions(
            name='placesresourcemediaevents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='resourceactivitycitationevents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='resourceactivitymediaevents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='resourceresourceevents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'managed': True, 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcesactivityevents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='resourcescitationevents',
            options={'managed': True, 'verbose_name': 'Resource - Citation', 'verbose_name_plural': 'Resources - Citations'},
        ),
        migrations.AlterModelOptions(
            name='resourcesmediaevents',
            options={'managed': True, 'verbose_name': 'Resource - Medium', 'verbose_name_plural': 'Resources - Media'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
