# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 23:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0003_auto_20170919_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='DigitizedBy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='digitized by'),
        ),
        migrations.AddField(
            model_name='locality',
            name='DigitizedDate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='digitized date'),
        ),
        migrations.AddField(
            model_name='locality',
            name='Source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='locality',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=3857, verbose_name='Place Geometry'),
        ),
    ]
