# Generated by Django 3.2.13 on 2023-01-19 23:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TEKDB", "0006_trigram_unaccent_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="citations",
            name="rawcitation",
            field=ckeditor.fields.RichTextField(
                blank=True,
                db_column="rawcitation",
                help_text="If you have the text for a bibliographic citation already formatted as you'd like it, please share it here.",
                null=True,
                verbose_name="Raw, formatted bibliographic citation",
            ),
        ),
    ]
