# Generated by Django 3.2.25 on 2024-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0010_auto_20231106_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_search_rank', models.FloatField(default=0.01)),
                ('min_search_similarity', models.FloatField(default=0.1)),
            ],
        ),
    ]
