# Generated by Django 3.2.25 on 2024-10-25 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TEKDB", "0017_auto_20241016_1552"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchSettings",
        ),
    ]
