# Generated by Django 3.2.25 on 2024-11-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0018_auto_20241022_1653'),
        ('TEKDB', '0018_delete_searchsettings'),
    ]

    operations = [
    ]
