# Generated by Django 3.2.25 on 2024-12-18 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0019_merge_20241126_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediabulkupload',
            name='mediabulkdate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date'),
        ),
    ]
