# Generated by Django 4.2.17 on 2024-12-24 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TEKDB", "0020_alter_media_mediabulkupload"),
        ("TEKDB", "0020_alter_mediabulkupload_mediabulkdate"),
    ]

    operations = []
