# Generated by Django 4.2.16 on 2025-05-08 21:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0023_alter_mediabulkupload_mediabulkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='comments',
            field=tinymce.models.HTMLField(blank=True, db_column='comments', null=True),
        ),
        migrations.AlterField(
            model_name='citations',
            name='rawcitation',
            field=tinymce.models.HTMLField(blank=True, db_column='rawcitation', help_text="If you have the text for a bibliographic citation already formatted as you'd like it, please share it here.", null=True, verbose_name='Raw, formatted bibliographic citation'),
        ),
        migrations.AlterField(
            model_name='media',
            name='mediadescription',
            field=tinymce.models.HTMLField(blank=True, db_column='mediadescription', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resourcesactivityevents',
            name='activitylongdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='activitylongdescription', null=True, verbose_name='full activity description'),
        ),
        migrations.AlterField(
            model_name='resourcesactivityevents',
            name='relationshipdescription',
            field=tinymce.models.HTMLField(blank=True, db_column='relationshipdescription', null=True, verbose_name='excerpt'),
        ),
    ]
