# Generated by Django 4.2.27 on 2026-01-30 19:11

from django.db import migrations, models
import django_resumable_async_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0025_alter_mediabulkupload_mediabulkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediafile',
            field=django_resumable_async_upload.models.AsyncFileField(blank=True, db_column='mediafile', max_files=1, max_length=255, null=True, upload_to='', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='mediabulkupload',
            name='mediabulkname',
            field=models.CharField(blank=True, default='Bulk Upload on 2026-01-30', max_length=255, null=True, verbose_name='name'),
        ),
    ]
