# Generated by Django 4.2.29 on 2026-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0026_alter_media_mediafile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediabulkupload',
            name='mediabulkname',
            field=models.CharField(blank=True, default='Bulk Media Upload', max_length=255, null=True, verbose_name='name'),
        ),
    ]
