# Generated by Django 4.2.30 on 2026-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0027_alter_mediabulkupload_mediabulkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='preparedfor',
            field=models.CharField(blank=True, db_column='preparedfor', max_length=100, null=True, verbose_name='prepared for'),
        ),
    ]
