# Generated by Django 4.2.30 on 2026-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0028_alter_citations_preparedfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='media',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='places',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='resources',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='resourcesactivityevents',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='keywords'),
        ),
    ]
