# Generated by Django 3.2.8 on 2021-10-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='accesslevel',
            field=models.ForeignKey(blank=True, db_column='accesslevel', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Accounts.useraccess', verbose_name='access level'),
        ),
    ]
