# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TEKDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placealtindigenousname',
            fields=[
                ('altindigenousnameid', models.AutoField(db_column='AltIndigenousNameID', primary_key=True, serialize=False)),
                ('altindigenousname', models.CharField(blank=True, db_column='AltIndigenousName', max_length=255, null=True, verbose_name='alternate indigenous name')),
                ('placeid', models.ForeignKey(blank=True, db_column='PlaceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TEKDB.Places')),
            ],
            options={
                'db_table': 'Placealtindigenousname',
                'verbose_name': 'Place - Indigenous Name',
                'verbose_name_plural': 'Places - Indigenous Names',
                'managed': True,
            },
        ),
    ]
