# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name_plural': 'Page Contents'},
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='is_html',
            field=models.BooleanField(default=False, help_text='Select this if you want to use raw HTML instead. For this option, use the "HTML content" window below.'),
        ),
    ]
