# Generated by Django 4.2.16 on 2025-05-08 20:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("explore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
