name: Publish to ECR and Deploy to App Runner
on:
  push:
    branches: [develop] # Trigger workflow on git push to develop branch
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:  
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          # Use GitHub OIDC provider
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1        
      
      # steps to build, tag, and push Docker image to ECR
      # tag with both latest and git sha
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tekdb
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image-latest::$ECR_REGISTRY/$ECR_REPOSITORY:latest"  
          
      # - name: Deploy to App Runner Image
      #   id: deploy-apprunner
      #   uses: awslabs/amazon-app-runner-deploy@main
      #   with:
      #     service: app-runner-git-deploy-service
      #     image: ${{ steps.build-image.outputs.image }}
      #     access-role-arn: ${{ secrets.ROLE_ARN }}
      #     region: ${{ secrets.AWS_REGION }}
      #     cpu : 1
      #     memory : 2
      #     wait-for-service-stability-seconds: 1200
      
      # - name: App Runner URL
      #   run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service-url }}"